# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RCTPdf' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'react-native-blob-util', '0.13.10'

  # Pods for RCTPdf

end
